config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about" ,as: "about"
  get 'home/top' => "homes#top"
  devise_for :users
  root to:'homes#top'
  resources :books, only: [:new, :index, :show,:create,:destroy,:edit,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users,only:[:show, :edit,:index,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body,length:{ maximum: 200},presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  # def get_image
  #   if image.attached?
  #     image
  #   else
  #     'no_image.jpg'
  #   end
  # end

  # def get_image
  #   unless image.attached?
  #     file_path = Rails.root.join('app/assets/images/no_image.jpg')
  #     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   image
  # end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true, uniqueness: { scope: :book_id }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name,length: { minimum: 2, maximum: 20 } ,presence: true,uniqueness: true
  validates:introduction, length: {maximum: 50}

  has_one_attached :profile_image


def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end



  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]= "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "books/edit"
    end
  end

  def index
    @books = Book.all
    @book=Book.new
    @post_comment = PostComment.new
  end

  def show
    @book=Book.find(params[:id])
    @bookNew =Book.new
    @books = Book.all
    @book_comment = BookComment.new
  end

  def destroy
   book =Book.find(params[:id])
   book.destroy
   redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book=Book.find(params[:id])
    user_id =book.user.id
    unless user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  def index
    @user = User.find(current_user.id)
    @books = @user.books
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "users/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
 <div class="col-md-3">
  <h2>User info</h2>

  <%= image_tag current_user.get_profile_image(100,100) %>



  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>

<div class="row">
  <%= link_to edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block' do %>
  <i class="fas fa-user-cog"></i>
  <% end %>
</div>



  <h2>New book</h2>
  <!-- form_with部分 -->
 <%= form_with model: book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>
  <div>
    <%= f.submit 'Create Book' %>
  </div>
  <% end %>
  </div>

  <style>
    .btn-block {
      display:block;
      width:100%;
    }

    .row {
      display: flex;
      flex-wrap: wrap;
      margin-right: -15px;
      margin-left: -15px;

    }
  </style>

app/views/books/edit.html.erb
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>Editing Book</h2>
<% if @book.errors.any? %>
 <div>
 <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>
<%= form_with model: @book do |f| %>

  <label for="inputTitle">Title</label>
  <p><%= f.text_field :title, autofocus: true, id:"inputTitle"%></p>

  <label for="inputOpinion">Opinion</label>
  <p><%= f.text_area :body, autofocus: true, id:"Inputbody"%></p>
  <p>
  <%= f.submit "Update Book" %>
  </p>
  <p>
    <%= link_to"Show",book_path(@book.id) %>|<%= link_to"Back",books_path %>
  </p>
<% end %>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<% if @book.errors.any? %>
 <div>
 <h2> <%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>
</div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'list', book: @book %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id), class: 'nav-link' do%>
        <%= image_tag book.user.get_profile_image(100,100) %></td>
        <% end %>
      <td>
        <%= link_to book_path(book.id),class: 'nav-link' do%>
        <%= book.title%>
        <% end %>
      </td>
      <td><%= book.body%></td>
      <td>
        <% if book.favorited_by?(current_user) %>
         <p>
          <%= link_to  book_favorites_path(book), method: :delete do %>
          <i class="fas fa-heart"></i><%= book.favorites.count %>
          <% end %>
         </p>
        <% else %>
         <p>
        <%= link_to  book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i><%= book.favorites.count %>
        <% end %>
         </p>
        <% end %>
      </td>
      <td>
         <p>コメント数：<%= book.book_comments.count %></p>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>

</div>

</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div><%= flash[:notice] %></div>


<div class="container px-5 px-sm-0">
<div class="row">


<div class="col-md-3">
  <h2>User info</h2>

  <%= image_tag @book.user.get_profile_image(100,100) %>



  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @book.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @book.user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class ="row">
  <%= link_to edit_user_path(@book.user.id), class: 'btn btn-outline-secondary btn-block' do %>
  <i class="fas fa-user-cog"></i>
  <% end %>
  </div>


  <h2>New book</h2>
  <!-- form_with部分 -->
 <%= form_with model: @bookNew do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>
  <div>
    <%= f.submit 'Create Book' %>
  </div>
  <% end %>
  </div>


<div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
  <table class="table table-hover table-inverse">


  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@book.user.id), class: 'nav-link' do%>
        <%= image_tag @book.user.get_profile_image(100,100) %><p><%= @book.user.name%></p>
        <% end %>
      </td>
      <td><%= @book.title%></td>
      <td><%= @book.body%></td>
      <td>
        <% if @book.favorited_by?(current_user) %>
         <p>
          <%= link_to  book_favorites_path(@book), method: :delete do %>
          <i class="fas fa-heart"></i><%= @book.favorites.count %>
          <% end %>
         </p>
        <% else %>
         <p>
        <%= link_to  book_favorites_path(@book), method: :post do %>
          <i class="far fa-heart"></i><%= @book.favorites.count %>
        <% end %>
         </p>
        <% end %>
      </td>
      <td>
         <p>コメント数：<%= @book.book_comments.count %></p>
      </td>
      <td class><%if @book.user == current_user %>
          <%= link_to"Edit", edit_book_path(@book), class: 'btn btn-success' %>
          <% end %>
      </td>
      <td><% if @book.user == current_user %>
          <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？" , class: 'btn btn-danger' %>
          <% end %>
      </td>
    </tr>

  </tbody>
  </table>

  <div>
    <% @book.book_comments.each do |book_comment| %>
      <%= image_tag book_comment.user.get_profile_image(100,100) %><%= book_comment.comment %>
      <% if book_comment.user == current_user %>
          <%= link_to "Destroy",book_book_comment_path(book_comment.book, book_comment), method: :delete, "data-confirm" => "本当に削除しますか？" , class: 'btn btn-danger' %>
      <% end %>
      <td>
        <%= link_to user_path(book_comment.user.id), class: 'nav-link' do%>
        <%= book_comment.user.name %>
        <% end %>
      </td>
    <% end %>
  </div>
  <div>
    <%= form_with model: [@book, @book_comment] do |f| %>
      <%= f.text_area :comment, rows: '5'%>
      <div></div>
      <%= f.submit "送信" %>
    <% end %>
  </div>
  </div>
    </div>
      </div>

  <style>
    .btn-block{
      display:block;
      width:100%;
    }

    .row {
      display: flex;
      flex-wrap: wrap;
      margin-right: -15px;
      margin-left: -15px;

    }
  </style>

app/views/homes/about.html.erb
<div class="outer">
    <div class= "main">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
</div>

<style>
 .main {
      display: inline-block;
      text-align: left;
      line-height:1.5;
      margin-top: 10px;
      margin-bottom:30px;
    }

.outer{
  text-align: center;
}
</style>

app/views/homes/top.html.erb
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<div class="outer">
    <div class= "main">
        <h1>welcome to <i class=".fas.fa-book"></i><strong>Bookers</strong>!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
    </div>


    <div class="d-grid gap-2">
    <%= link_to "Log in", new_user_session_path, class: 'btn btn-info' %>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success' %>
    </div>

</div>


<style>
 .main {
      display: inline-block;
      text-align: left;
      line-height:1.5;
    }

.outer{
  text-align: center;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body>
 <header class="bg-dark shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
         <a class="navbar-brand p-3 text-light" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">

              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do%>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>

            <li class="nav-item">

              <%= link_to users_path, class: 'nav-link text-light' do%>
              <i class="fas fa-users"></i>
              Users
               <% end %>
            </li>

            <li class="nav-item">

              <%= link_to books_path,class: 'nav-link text-light' do%>
              <i class="fas fa-book-open"></i>
              Books
              <% end %>
            </li>

            <li class="nav-item">

              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do%>
               <i class="fas fa-sign-out-alt"></i>
               Log out
              <% end %>
            </li>

            <% else %>
             <li class="nav-item">

              <%= link_to root_path, class: 'nav-link text-light' do%>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>
             <li class="nav-item">

              <%= link_to about_path, class: 'nav-link text-light' do%>
              <i class="fas fa-link"></i>
              About
              <% end %>
            </li>
            <li class="nav-item">

              <%= link_to new_user_registration_path, class: 'nav-link text-light' do%>
              <i class="fas fa-user-plus"></i>
              Sign up
              <% end %>
            </li>
            <li class="nav-item">

              <%= link_to new_user_session_path, class: 'nav-link text-light' do%>
              <i class="fas fa-sign-in-alt"></i>
              Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
       <%= yield %>
    </main>

<footer class="footer">
  <div class="container text-center">
    <p class="text">CopyRight Infratop.inc</p>
  </div>
</footer>

  </body>
   <style>


   </style>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
 <div>
 <h2> <%= @user.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>
<%= form_with model: @user do |f| %>

  <label for="inputName">Name</label>
  <p><%= f.text_field :name, autofocus: true, id:"inputName"%></p>
  <label for="inputImage">Image</label>
  <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
  <label for="inputIntroduction">Introduction</label>
  <p><%= f.text_area :introduction, autofocus: true, id:"introduction"%></p>
  <p>
  <%= f.submit "Update User" %>
  </p>
<% end %>
</div>
</div>

app/views/users/index.html.erb
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'books/list', book: @book%>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </thead>

  <tbody>
    <% @users.each do |book| %>
    <tr>
      <td><%= image_tag book.get_profile_image(100,100) %></td>
      <td><%= book.name%></td>
      <td><%= link_to"Show",user_path(book.id) %></td>
    </tr>
    <% end %>
  </tbody>
  </table>

</div>

</div>
</div>

app/views/users/show.html.erb
<div><%= flash[:notice] %></div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<div class="container px-5 px-sm-0">
<div class="row">

 <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @user.get_profile_image(100,100) %>



  <table class="table">

    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>


  <div class ="row">
  <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
  <i class="fas fa-user-cog"></i>
  <% end %>
  </div>


  <h2>New book</h2>
  <!-- form_with部分 -->
 <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>
  <div>
    <%= f.submit 'Create Book' %>
  </div>
  <% end %>
  </div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
         <%= link_to user_path(book.user.id),class: 'nav-link' do%>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
        </td>
      <td>
        <%= link_to book_path(book.id),class: 'nav-link' do%>
        <%= book.title%>
        <% end %>
      </td>
      <td><%= book.body%></td>
      <td>
         <% if book.favorited_by?(current_user) %>
         <p>
          <%= link_to  book_favorites_path(book), method: :delete do %>
          <i class="fas fa-heart"></i><%= book.favorites.count %>
          <% end %>
         </p>
        <% else %>
         <p>
        <%= link_to  book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i><%= book.favorites.count %>
        <% end %>
         </p>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>

</div>

</div>
</div>

<style>
    .btn-block{
      display:block;
      width:100%;
    }

    .row {
      display: flex;
      flex-wrap: wrap;
      margin-right: -15px;
      margin-left: -15px;

    }
 </style>